name: 'IDF_dbt'
version: '1.0.0'

profile: 'IDF_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:  
  - "target"
  - "dbt_packages"


models:
  IDF_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
